Update use-secrets.yml

diff --git a/.github/workflows/use-secrets.yml b/.github/workflows/use-secrets.yml
--- a/.github/workflows/use-secrets.yml
+++ b/.github/workflows/use-secrets.yml
@@ -14,3 +14,9 @@ jobs:
         uses: ./.github/actions/check-secrets-action
         with:
           secrets-context: ${{ secrets.TOP }}
+      - name: Check for errors
+        run: |
+          if [ ${{ steps.check-secrets.outcome }} != "success" ]; then
+            echo "Error: check-secrets failed"
+            exit 1
+          fi
